spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
    name: 'fornecedor'
    
    
  jpa:
    hibernate:
      ddl-auto: update
